### ISSUE TITLE
Ошибка с работой страницы Иконки в режиме инкогнито

### ISSUE THREAD

**Issue by Ser-Gen** [hyoo-ru/mol.hyoo.ru#1]
Открыл сайт в хроме 95.0.4638.69 в режиме **инкогнито**.
https://mol.hyoo.ru/

Нажал на ссылку «Иконки».

В адресе появился хеш
https://mol.hyoo.ru/#!section=icons

Правая часть страницы стала белой.

В консоли вижу ошибку
```
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at https://nin-jin.github.io/mol_icon/web.js:283:5
    at https://nin-jin.github.io/mol_icon/web.js:287:3
```

![image](https://user-images.githubusercontent.com/1856145/140505245-11f302a7-3433-4559-9432-df155b950229.png)

**Comment by nin-jin** [comment]
Убрал использование сессионного хранилища из логирования в этом приложении. В остальных такой проблемы быть не должно.

**Comment by Ser-Gen** [comment]
Теперь страница открывается, хоть и без тёмной темы.
В консоли ошибка, которая не блокирует работу.

```
nin-jin.github.io/:1
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://nin-jin.github.io/mol_icon/') with script ('https://nin-jin.github.io/mol_icon/web.js'): The user denied permission to use Service Worker.
```

Ещё одна неблокирующая ошибка нашлась в Рисовалке
https://mol.hyoo.ru/#!demo=mol_switch_demo/section=apps/app=draw/uri=https%3A%2F%2Fdraw.hyoo.ru%2F%23mol_lights%3Dfalse

```
attributes.ts:23 
Error: <path> attribute d: Expected number, "M NaN NaN L NaN Na…".
```

**Comment by nin-jin** [comment]
Хех, обожаю IEEE 754.)
